# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


jobs:  
- job: preps
  displayName: Preparations
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.0.0'
    displayName: 'Install Node.js'

  - script: |
      sudo npm install -g aws-cdk
      pip install -r requirements.txt
      echo list app
      cdk ls
      #cdk synth
    displayName: 'npm install'
  - script: |
      echo list app
      cdk ls
    displayName: 'cdk ls'  
  - task: AWSShellScript@1
    inputs:
      awsCredentials: 'AWS-SANDBOX'
      regionName: 'eu-central-1'
      scriptType: 'inline'
      # inlineScript: 'cdk deploy --ci --require-approval never'
      inlineScript: 'cdk diff'
      disableAutoCwd: true
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      failOnStandardError: false
    displayName: 'cdk diff'

  - task: AWSShellScript@1
    inputs:
      awsCredentials: 'AWS-SANDBOX'
      regionName: 'eu-central-1'
      scriptType: 'inline'
      # inlineScript: 'cdk deploy --ci --require-approval never'
      inlineScript: 'cdk deploy'
      disableAutoCwd: true
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      failOnStandardError: false
    displayName: 'cdk deploy'


  

- job: doSomething
  displayName: Do Something
  steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
  
- job: waitForValidation
  displayName: wait for external validation
  dependsOn: doSomething
  pool: server
  timeoutInMinutes: 3600
  steps:
  - task: ManualValidation@0
    inputs:
      notifyUsers: 1robroos@gmail.com
      instructions: 'please validate'

- job: afterForValidation
  displayName: Do Something After Validation
  dependsOn: waitforValidation
  steps:
  - script: echo Validation Completed!
    displayName: 'Run a one-line script'

    