trigger:
  - master
# startput voor je pipeline


pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '22.0.0'

# - task: UseRubyVersion@0
#   inputs:
#     versionSpec: '>= 2.4'

- script: |
    echo "Installing packages"
    sudo npm install -g aws-cdk
#    sudo gem install cfn-nag    
  displayName: 'Installing aws cdk'

# - script: |
#     echo "Installing project dependencies"
#     sudo npm install
#     sudo npm run build    
#   displayName: 'Installing project dependencies'

# - task: AWSShellScript@1
#   inputs:
#     awsCredentials: 'AWS-SANDBOX'
#     regionName: 'eu-central-1'
#     scriptType: 'inline'
#     inlineScript: |
#       echo "Running validations"
#       cdk synth -o out
#       cd out
#       fname=$(find *.template.json)
#       echo "Testing output with cfn-nag-scan"
#       cfn_nag_scan --input-path $fname
#   displayName: 'Validating AWS CDK output'

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS-SANDBOX'
    regionName: 'eu-central-1'
    scriptType: 'inline'
    inlineScript: |
      echo "Generating CDK diff file"
      cdk diff -o out -c aws-cdk:enableDiffNoFail=true --no-color "*" 2>&1 | sed -n '/Resources/,/Outputs/p' | sed 's/├/\+/g; s/│/|/g; s/─/-/g; s/└/`/g' | head -n -1 | tee output.log
      sed -i '1 i\```bash' output.log
      sed -i -e '$a```' output.log
  displayName: 'Generating CDK diff file'

# # Manual intervention v8
# # Pause deployment and wait for manual intervention.
# - task: ManualIntervention@8
#   inputs:
#     instructions: "Make a choice!" # string. Instructions. 
#     emailRecipients: 1robroos@gmail.com # string. Notify users. 
#     onTimeout: 'reject' # 'reject' | 'resume'. On timeout. Default: reject. Automatically rejects or resumes the manual intervention after it is pending for the specified timeout, or 60 days, whichever is earlier.
#   displayName: 'Manual intervention'

- job: waitForValidation
  displayName: wait for external validation
  dependsOn: preps
  pool: server #   pool: server # note: the value 'server' is a reserved keyword which indicates this is an agentless job
  timeoutInMinutes: 3600
  steps:
  - task: ManualValidation@0
    inputs:
      notifyUsers: 1robroos@gmail.com
      instructions: 'please validate'

- job: afterForValidation
  displayName: Do Something After Validation
  dependsOn: waitforValidation
  steps:
  - script: echo Validation Completed!
    displayName: 'Run cdk deploy'
  - task: AWSShellScript@1
    inputs:
      awsCredentials: 'AWS-SANDBOX'
      regionName: 'eu-central-1'
      scriptType: 'inline'
      inlineScript: 'cdk deploy'
      disableAutoCwd: true
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      failOnStandardError: false
    displayName: 'cdk deploy'
