# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.0.0'
  displayName: 'Install Node.js'

- script: |
    sudo npm install -g aws-cdk
    pip install -r requirements.txt
    echo list app
    cdk ls
    #cdk synth
  displayName: 'npm install and cdk ls'
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS-SANDBOX'
    regionName: 'eu-central-1'
    scriptType: 'inline'
    # inlineScript: 'cdk deploy --ci --require-approval never'
    inlineScript: 'cdk diff'
    disableAutoCwd: true
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    failOnStandardError: false
  displayName: 'cdk diff'


