trigger:
  - dev
# startput voor je pipeline

# pr:
#   - dev


pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '22.0.0'

# - task: UseRubyVersion@0
#   inputs:
#     versionSpec: '>= 2.4'

- script: |
    echo "Installing packages"
    sudo npm install -g aws-cdk
#    sudo gem install cfn-nag    
  displayName: 'Installing aws cdk'

# - script: |
#     echo "Installing project dependencies"
#     sudo npm install
#     sudo npm run build    
#   displayName: 'Installing project dependencies'

# - task: AWSShellScript@1
#   inputs:
#     awsCredentials: 'AWS-SANDBOX'
#     regionName: 'eu-central-1'
#     scriptType: 'inline'
#     inlineScript: |
#       echo "Running validations"
#       cdk synth -o out
#       cd out
#       fname=$(find *.template.json)
#       echo "Testing output with cfn-nag-scan"
#       cfn_nag_scan --input-path $fname
#   displayName: 'Validating AWS CDK output'

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS-SANDBOX'
    regionName: 'eu-central-1'
    scriptType: 'inline'
    inlineScript: |
      echo "Generating CDK diff file"
      cdk diff -o out -c aws-cdk:enableDiffNoFail=true --no-color "*" 2>&1 | sed -n '/Resources/,/Outputs/p' | sed 's/├/\+/g; s/│/|/g; s/─/-/g; s/└/`/g' | head -n -1 | tee output.log
      sed -i '1 i\```bash' output.log
      sed -i -e '$a```' output.log
  displayName: 'Generating CDK diff file'

