# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'  # Specify a Microsoft-hosted pool using the vmImage property.

jobs:  
- job: preps
  displayName: Preparations
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.0.0'
    displayName: 'Install Node.js'

  - script: |
      sudo npm install -g aws-cdk
      pip install -r requirements.txt
      #cdk synth
    displayName: 'npm install'
  - script: |
      echo list app
      cdk ls
    displayName: 'cdk ls'  
  - task: AWSShellScript@1
    inputs:
      awsCredentials: 'AWS-SANDBOX'
      regionName: 'eu-central-1'
      scriptType: 'inline'
      inlineScript: 'cdk diff'
      disableAutoCwd: true
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      failOnStandardError: false
    displayName: 'cdk diff'
  # - task: ManualValidation@0
  #   timeoutInMinutes: 1440 # task times out in 1 day
  #   inputs:
  #     notifyUsers: 1robroos@gmail.com
  #     instructions: 'please validate'
  #     onTimeout: 'reject' # 'resume'
  - task: AWSShellScript@1
    inputs:
      awsCredentials: 'AWS-SANDBOX'
      regionName: 'eu-central-1'
      scriptType: 'inline'
      inlineScript: 'cdk deploy'
      disableAutoCwd: true
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      failOnStandardError: false
    displayName: 'cdk deploy'



    # two jobs solution: checkout also runs twice and npm install needs to run twice . 
# on microsoft hosted agents,  The virtual machine is discarded after one job 
# (which means any change that a job makes to the virtual machine file system, such as checking out code, will be unavailable to the next job). 
    # Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# trigger:
#   - master
  
#   pool:
#     vmImage: 'ubuntu-latest'
  
#   jobs:  
#   - job: preps
#     displayName: Preparations
#     steps:
#     - task: NodeTool@0
#       inputs:
#         versionSpec: '22.0.0'
#       displayName: 'Install Node.js'
  
#     - script: |
#         sudo npm install -g aws-cdk
#         pip install -r requirements.txt
#         #cdk synth
#       displayName: 'npm install'
#     - script: |
#         echo list app
#         cdk ls
#       displayName: 'cdk ls'  
#     - task: AWSShellScript@1
#       inputs:
#         awsCredentials: 'AWS-SANDBOX'
#         regionName: 'eu-central-1'
#         scriptType: 'inline'
#         inlineScript: 'cdk diff'
#         disableAutoCwd: true
#         workingDirectory: '$(System.DefaultWorkingDirectory)'
#         failOnStandardError: false
#       displayName: 'cdk diff'
    
#   - job: waitForValidation
#     displayName: wait for external validation
#     dependsOn: preps
#     pool: server #   pool: server # note: the value 'server' is a reserved keyword which indicates this is an agentless job
#     timeoutInMinutes: 3600
#     steps:
#     - task: ManualValidation@0
#       inputs:
#         notifyUsers: 1robroos@gmail.com
#         instructions: 'please validate'
  
#   - job: afterForValidation
#     displayName: Do Something After Validation
#     dependsOn: waitforValidation
#     steps:
#     - script: echo Validation Completed!
#       displayName: 'Run cdk deploy'
#     - task: AWSShellScript@1
#       inputs:
#         awsCredentials: 'AWS-SANDBOX'
#         regionName: 'eu-central-1'
#         scriptType: 'inline'
#         inlineScript: 'cdk deploy'
#         disableAutoCwd: true
#         workingDirectory: '$(System.DefaultWorkingDirectory)'
#         failOnStandardError: false
#       displayName: 'cdk deploy'
  
  
      
    